In [1]:
import numpy as np

In [2]:
data = np.array(np.random.randint(1, 100, size=25)).reshape(5, 5)

print("Original data matrix:")
print(data)

data[1], data[3] = data[3].copy(), data[1].copy()

print("\nData matrix with second and fourth rows swapped:")
print(data)

Original data matrix:
[[81 37  8 98 90]
 [ 9 76 97  3 34]
 [54 31 51 27 61]
 [21 14 55 10 72]
 [57 23 64 96 31]]

Data matrix with second and fourth rows swapped:
[[81 37  8 98 90]
 [21 14 55 10 72]
 [54 31 51 27 61]
 [ 9 76 97  3 34]
 [57 23 64 96 31]]


In [3]:
data = np.array(np.random.randint(1, 100, size=25)).reshape(5, 5)


print("Original data matrix:")
print(data)

min_val = np.min(data)
max_val = np.max(data)
normalized_data = (data - min_val) / (max_val - min_val)

print("\nNormalized data matrix:")
print(normalized_data)

Original data matrix:
[[20 97 34 54 68]
 [32 41 64 15 26]
 [55 56 78 39 44]
 [53 78 20 29  7]
 [38 55 39 13 64]]

Normalized data matrix:
[[0.14444444 1.         0.3        0.52222222 0.67777778]
 [0.27777778 0.37777778 0.63333333 0.08888889 0.21111111]
 [0.53333333 0.54444444 0.78888889 0.35555556 0.41111111]
 [0.51111111 0.78888889 0.14444444 0.24444444 0.        ]
 [0.34444444 0.53333333 0.35555556 0.06666667 0.63333333]]


In [4]:
data = np.array(np.random.randint(1, 100, size=25)).reshape(5, 5)

print("Original data matrix:")
print(data)

mean = np.mean(data)
std = np.std(data)

z_score_normalized_data = (data - mean) / std

print("\nZ-score normalized data matrix:")
print(z_score_normalized_data)

Original data matrix:
[[55 27 72 47 63]
 [ 2 68  6 24 93]
 [50 17 77 96 28]
 [32 46 21 39 65]
 [36 49 95 98 67]]

Z-score normalized data matrix:
[[ 0.14782671 -0.86667031  0.76377132 -0.14202958  0.437683  ]
 [-1.77247121  0.61884318 -1.62754307 -0.97536642  1.52464409]
 [-0.03333347 -1.22899067  0.94493151  1.63334019 -0.83043827]
 [-0.68551013 -0.17826162 -1.08406252 -0.43188587  0.51014707]
 [-0.54058198 -0.06956551  1.59710816  1.70580427  0.58261114]]


In [5]:
data = np.array(np.random.randint(1, 100, size=25)).reshape(5, 5)

print("Original data matrix:")
print(data)

data_vector = np.ravel(data)

sub_arrays = np.array_split(data_vector, 5)

print("\nSub-arrays:")
for sub_array in sub_arrays:
    print(sub_array)

Original data matrix:
[[27 12 59 60 30]
 [49 40 84 80 86]
 [41 15 22 13  5]
 [53 91 68 52 73]
 [95 32 91 92 56]]

Sub-arrays:
[27 12 59 60 30]
[49 40 84 80 86]
[41 15 22 13  5]
[53 91 68 52 73]
[95 32 91 92 56]


In [6]:
vector1 = np.array([3, 5, 6, 7, 8])
vector2 = np.array([2, 4, 6, 8, 10])

dot_product = np.dot(vector1, vector2)

print("Dot product:", dot_product)

Dot product: 198


In [7]:
data = np.array(np.random.randint(1, 100, size=25)).reshape(5, 5)

data2 = np.array([[2, 3, 4],
                  [5, 6, 7],
                  [8, 9, 10]])

data_part = data[:3, :3]
result = np.dot(data_part, data2)
print(result)

[[ 764  951 1138]
 [ 806  969 1132]
 [ 289  354  419]]


In [8]:
identity_matrix = np.identity(3)

scaled_matrix = 2 * identity_matrix
inverse_matrix = np.linalg.inv(scaled_matrix)
print(inverse_matrix)

[[0.5 0.  0. ]
 [0.  0.5 0. ]
 [0.  0.  0.5]]


In [9]:
data = np.array(np.random.randint(1, 100, size=25)).reshape(5, 5)
print("Original data matrix:")
print(data)

missing_indices = np.random.choice(data.size, 5, replace=False)
data.ravel()[missing_indices] = np.nan

missing_row_indices, missing_col_indices = np.unravel_index(missing_indices, data.shape)

print("\nIndices of missing values:")
print(missing_row_indices, missing_col_indices)

Original data matrix:
[[43 48 69 71  7]
 [50 25 75 72 29]
 [73 93 95  3 93]
 [33 44 46 57 66]
 [16 54 11 97 54]]


ValueError: cannot convert float NaN to integer

In [10]:
data = np.array(np.random.randint(1, 100, size=25)).reshape(5, 5)

print("Original data matrix:")
print(data)

missing_indices = np.random.choice(data.size, 5, replace=False)
data.ravel()[missing_indices] = np.nan

mean_value = np.nanmean(data)

data[np.isnan(data)] = mean_value

print("\nData matrix with missing values replaced:")
print(data)

Original data matrix:
[[55 79 50 57 96]
 [85 54 57 94 87]
 [84 97  9 28 24]
 [39 42 17 48 31]
 [ 6 90 73 16 97]]


ValueError: cannot convert float NaN to integer