In [5]:
import numpy as np

In [8]:
vector_of_zeros = np.zeros(10)

In [9]:
print(vector_of_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
array = np.zeros(10, dtype=np.float64)

In [11]:
memory_size = array.size * array.itemsize

In [12]:
print(memory_size)

80


In [15]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [16]:
vector = np.arange(10, 50)

print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [17]:
original_vector = np.arange(10, 50)

reversed_vector = original_vector[::-1]

print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [18]:
linear_array = np.arange(9)
matrix = linear_array.reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
input_array = np.array([1, 2, 0, 0, 4, 0])

indices = np.nonzero(input_array)

print(indices)

(array([0, 1, 4], dtype=int64),)


In [20]:
identity_matrix = np.eye(3)

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
row_values = np.arange(5)

matrix = np.tile(row_values, (5, 1))

print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [22]:
vector = np.linspace(0.1, 0.9, 10)

print(vector)

[0.1        0.18888889 0.27777778 0.36666667 0.45555556 0.54444444
 0.63333333 0.72222222 0.81111111 0.9       ]


In [23]:
random_vector = np.random.rand(10)

sorted_vector = np.sort(random_vector)

print(sorted_vector)

[0.34209004 0.43910156 0.43935693 0.49051296 0.5716377  0.58236593
 0.6266255  0.74453196 0.77700356 0.96919275]


In [24]:
int_types = [np.int8, np.int32, np.int64]

for int_type in int_types:
    info = np.iinfo(int_type)
    print(f"For {int_type.__name__}:")
    print(f"  Minimum: {info.min}")
    print(f"  Maximum: {info.max}")
    print()


float_types = [np.float32, np.float64]

for float_type in float_types:
    info = np.finfo(float_type)
    print(f"For {float_type.__name__}:")
    print(f"  Minimum: {info.min}")
    print(f"  Maximum: {info.max}")
    print()

For int8:
  Minimum: -128
  Maximum: 127

For int32:
  Minimum: -2147483648
  Maximum: 2147483647

For int64:
  Minimum: -9223372036854775808
  Maximum: 9223372036854775807

For float32:
  Minimum: -3.4028234663852886e+38
  Maximum: 3.4028234663852886e+38

For float64:
  Minimum: -1.7976931348623157e+308
  Maximum: 1.7976931348623157e+308



In [25]:
float_array = np.array([1.5, -2.7, 3.8, -4.2, 5.9], dtype=np.float32)

float_array = float_array.astype(np.int32, copy=False)

print(float_array)

[ 1 -2  3 -4  5]


In [26]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_means = np.mean(matrix, axis=1, keepdims=True)

matrix_centered = matrix - row_means

print(matrix_centered)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [27]:
import numpy as np

array = np.array([[4, 2, 7],
                  [1, 5, 9],
                  [6, 3, 8]])
n = 1

sorted_indices = np.argsort(array[:, n])

sorted_array = array[sorted_indices]

print(sorted_array)

[[4 2 7]
 [6 3 8]
 [1 5 9]]


In [28]:
array = np.array([[0, 1, 2],
                  [3, 4, 5],
                  [6, 7, 8]])

array[[0, 1]] = array[[1, 0]]

print(array)

[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [29]:
C = np.array([0, 2, 0, 1, 1, 0, 0, 3])

A = np.repeat(np.arange(len(C)), C)

print(A)

[1 1 3 4 7 7 7]
